<?php
	$SPM_Countries_Select = array(
		array("00", "Country not set"),
		array("AF", "Afghanistan"),
		array("AL", "Albania"),
		array("DZ", "Algeria"),
		array("AS", "American Samoa"),
		array("AD", "Andorra"),
		array("AO", "Angola"),
		array("AI", "Anguilla"),
		array("AQ", "Antarctica"),
		array("AG", "Antigua and Barbuda"),
		array("AR", "Argentina"),
		array("AM", "Armenia"),
		array("AW", "Aruba"),
		array("AU", "Australia"),
		array("AT", "Austria"),
		array("AZ", "Azerbaijan"),
		array("BS", "Bahamas"),
		array("BH", "Bahrain"),
		array("BD", "Bangladesh"),
		array("BB", "Barbados"),
		array("BY", "Belarus"),
		array("BE", "Belgium"),
		array("BZ", "Belize"),
		array("BJ", "Benin"),
		array("BM", "Bermuda"),
		array("BT", "Bhutan"),
		array("BO", "Bolivia"),
		array("BA", "Bosnia and Herzegovina"),
		array("BW", "Botswana"),
		array("BV", "Bouvet Island"),
		array("BR", "Brazil"),
		array("BQ", "British Antarctic Territory"),
		array("IO", "British Indian Ocean Territory"),
		array("VG", "British Virgin Islands"),
		array("BN", "Brunei"),
		array("BG", "Bulgaria"),
		array("BF", "Burkina Faso"),
		array("BI", "Burundi"),
		array("KH", "Cambodia"),
		array("CM", "Cameroon"),
		array("CA", "Canada"),
		array("CT", "Canton and Enderbury Islands"),
		array("CV", "Cape Verde"),
		array("KY", "Cayman Islands"),
		array("CF", "Central African Republic"),
		array("TD", "Chad"),
		array("CL", "Chile"),
		array("CN", "China"),
		array("CX", "Christmas Island"),
		array("CC", "Cocos [Keeling] Islands"),
		array("CO", "Colombia"),
		array("KM", "Comoros"),
		array("CG", "Congo - Brazzaville"),
		array("CD", "Congo - Kinshasa"),
		array("CK", "Cook Islands"),
		array("CR", "Costa Rica"),
		array("HR", "Croatia"),
		array("CU", "Cuba"),
		array("CY", "Cyprus"),
		array("CZ", "Czech Republic"),
		array("CI", "Côte d’Ivoire"),
		array("DK", "Denmark"),
		array("DJ", "Djibouti"),
		array("DM", "Dominica"),
		array("DO", "Dominican Republic"),
		array("NQ", "Dronning Maud Land"),
		array("DD", "East Germany"),
		array("EC", "Ecuador"),
		array("EG", "Egypt"),
		array("SV", "El Salvador"),
		array("GQ", "Equatorial Guinea"),
		array("ER", "Eritrea"),
		array("EE", "Estonia"),
		array("ET", "Ethiopia"),
		array("FK", "Falkland Islands"),
		array("FO", "Faroe Islands"),
		array("FJ", "Fiji"),
		array("FI", "Finland"),
		array("FR", "France"),
		array("GF", "French Guiana"),
		array("PF", "French Polynesia"),
		array("TF", "French Southern Territories"),
		array("FQ", "French Southern and Antarctic Territories"),
		array("GA", "Gabon"),
		array("GM", "Gambia"),
		array("GE", "Georgia"),
		array("DE", "Germany"),
		array("GH", "Ghana"),
		array("GI", "Gibraltar"),
		array("GR", "Greece"),
		array("GL", "Greenland"),
		array("GD", "Grenada"),
		array("GP", "Guadeloupe"),
		array("GU", "Guam"),
		array("GT", "Guatemala"),
		array("GG", "Guernsey"),
		array("GN", "Guinea"),
		array("GW", "Guinea-Bissau"),
		array("GY", "Guyana"),
		array("HT", "Haiti"),
		array("HM", "Heard Island and McDonald Islands"),
		array("HN", "Honduras"),
		array("HK", "Hong Kong SAR China"),
		array("HU", "Hungary"),
		array("IS", "Iceland"),
		array("IN", "India"),
		array("ID", "Indonesia"),
		array("IR", "Iran"),
		array("IQ", "Iraq"),
		array("IE", "Ireland"),
		array("IM", "Isle of Man"),
		array("IL", "Israel"),
		array("IT", "Italy"),
		array("JM", "Jamaica"),
		array("JP", "Japan"),
		array("JE", "Jersey"),
		array("JT", "Johnston Island"),
		array("JO", "Jordan"),
		array("KZ", "Kazakhstan"),
		array("KE", "Kenya"),
		array("KI", "Kiribati"),
		array("KW", "Kuwait"),
		array("KG", "Kyrgyzstan"),
		array("LA", "Laos"),
		array("LV", "Latvia"),
		array("LB", "Lebanon"),
		array("LS", "Lesotho"),
		array("LR", "Liberia"),
		array("LY", "Libya"),
		array("LI", "Liechtenstein"),
		array("LT", "Lithuania"),
		array("LU", "Luxembourg"),
		array("MO", "Macau SAR China"),
		array("MK", "Macedonia"),
		array("MG", "Madagascar"),
		array("MW", "Malawi"),
		array("MY", "Malaysia"),
		array("MV", "Maldives"),
		array("ML", "Mali"),
		array("MT", "Malta"),
		array("MH", "Marshall Islands"),
		array("MQ", "Martinique"),
		array("MR", "Mauritania"),
		array("MU", "Mauritius"),
		array("YT", "Mayotte"),
		array("FX", "Metropolitan France"),
		array("MX", "Mexico"),
		array("FM", "Micronesia"),
		array("MI", "Midway Islands"),
		array("MD", "Moldova"),
		array("MC", "Monaco"),
		array("MN", "Mongolia"),
		array("ME", "Montenegro"),
		array("MS", "Montserrat"),
		array("MA", "Morocco"),
		array("MZ", "Mozambique"),
		array("MM", "Myanmar [Burma]"),
		array("NA", "Namibia"),
		array("NR", "Nauru"),
		array("NP", "Nepal"),
		array("NL", "Netherlands"),
		array("AN", "Netherlands Antilles"),
		array("NT", "Neutral Zone"),
		array("NC", "New Caledonia"),
		array("NZ", "New Zealand"),
		array("NI", "Nicaragua"),
		array("NE", "Niger"),
		array("NG", "Nigeria"),
		array("NU", "Niue"),
		array("NF", "Norfolk Island"),
		array("KP", "North Korea"),
		array("VD", "North Vietnam"),
		array("MP", "Northern Mariana Islands"),
		array("NO", "Norway"),
		array("OM", "Oman"),
		array("PC", "Pacific Islands Trust Territory"),
		array("PK", "Pakistan"),
		array("PW", "Palau"),
		array("PS", "Palestinian Territories"),
		array("PA", "Panama"),
		array("PZ", "Panama Canal Zone"),
		array("PG", "Papua New Guinea"),
		array("PY", "Paraguay"),
		array("YD", "People's Democratic Republic of Yemen"),
		array("PE", "Peru"),
		array("PH", "Philippines"),
		array("PN", "Pitcairn Islands"),
		array("PL", "Poland"),
		array("PT", "Portugal"),
		array("PR", "Puerto Rico"),
		array("QA", "Qatar"),
		array("RO", "Romania"),
		array("RU", "Russia"),
		array("RW", "Rwanda"),
		array("RE", "Réunion"),
		array("BL", "Saint Barthélemy"),
		array("SH", "Saint Helena"),
		array("KN", "Saint Kitts and Nevis"),
		array("LC", "Saint Lucia"),
		array("MF", "Saint Martin"),
		array("PM", "Saint Pierre and Miquelon"),
		array("VC", "Saint Vincent and the Grenadines"),
		array("WS", "Samoa"),
		array("SM", "San Marino"),
		array("SA", "Saudi Arabia"),
		array("SN", "Senegal"),
		array("RS", "Serbia"),
		array("CS", "Serbia and Montenegro"),
		array("SC", "Seychelles"),
		array("SL", "Sierra Leone"),
		array("SG", "Singapore"),
		array("SK", "Slovakia"),
		array("SI", "Slovenia"),
		array("SB", "Solomon Islands"),
		array("SO", "Somalia"),
		array("ZA", "South Africa"),
		array("GS", "South Georgia and the South Sandwich Islands"),
		array("KR", "South Korea"),
		array("ES", "Spain"),
		array("LK", "Sri Lanka"),
		array("SD", "Sudan"),
		array("SR", "Suriname"),
		array("SJ", "Svalbard and Jan Mayen"),
		array("SZ", "Swaziland"),
		array("SE", "Sweden"),
		array("CH", "Switzerland"),
		array("SY", "Syria"),
		array("ST", "São Tomé and Príncipe"),
		array("TW", "Taiwan"),
		array("TJ", "Tajikistan"),
		array("TZ", "Tanzania"),
		array("TH", "Thailand"),
		array("TL", "Timor-Leste"),
		array("TG", "Togo"),
		array("TK", "Tokelau"),
		array("TO", "Tonga"),
		array("TT", "Trinidad and Tobago"),
		array("TN", "Tunisia"),
		array("TR", "Turkey"),
		array("TM", "Turkmenistan"),
		array("TC", "Turks and Caicos Islands"),
		array("TV", "Tuvalu"),
		array("UM", "U.S. Minor Outlying Islands"),
		array("PU", "U.S. Miscellaneous Pacific Islands"),
		array("VI", "U.S. Virgin Islands"),
		array("UG", "Uganda"),
		array("UA", "Ukraine (Україна)"),
		array("AE", "United Arab Emirates"),
		array("GB", "United Kingdom"),
		array("US", "United States"),
		array("ZZ", "Unknown or Invalid Region"),
		array("UY", "Uruguay"),
		array("UZ", "Uzbekistan"),
		array("VU", "Vanuatu"),
		array("VA", "Vatican City"),
		array("VE", "Venezuela"),
		array("VN", "Vietnam"),
		array("WK", "Wake Island"),
		array("WF", "Wallis and Futuna"),
		array("EH", "Western Sahara"),
		array("YE", "Yemen"),
		array("ZM", "Zambia"),
		array("ZW", "Zimbabwe"),
		array("AX", "Åland Islands"),
		array("WL", "Wirtland"),
		array("IND-S", "Коренной индусский программист")
	);
	$SPM_Countries_Get = array(
		"00" => "Country not set",
		"AF" => "Afghanistan",
		"AL" => "Albania",
		"DZ" => "Algeria",
		"AS" => "American Samoa",
		"AD" => "Andorra",
		"AO" => "Angola",
		"AI" => "Anguilla",
		"AQ" => "Antarctica",
		"AG" => "Antigua and Barbuda",
		"AR" => "Argentina",
		"AM" => "Armenia",
		"AW" => "Aruba",
		"AU" => "Australia",
		"AT" => "Austria",
		"AZ" => "Azerbaijan",
		"BS" => "Bahamas",
		"BH" => "Bahrain",
		"BD" => "Bangladesh",
		"BB" => "Barbados",
		"BY" => "Belarus",
		"BE" => "Belgium",
		"BZ" => "Belize",
		"BJ" => "Benin",
		"BM" => "Bermuda",
		"BT" => "Bhutan",
		"BO" => "Bolivia",
		"BA" => "Bosnia and Herzegovina",
		"BW" => "Botswana",
		"BV" => "Bouvet Island",
		"BR" => "Brazil",
		"BQ" => "British Antarctic Territory",
		"IO" => "British Indian Ocean Territory",
		"VG" => "British Virgin Islands",
		"BN" => "Brunei",
		"BG" => "Bulgaria",
		"BF" => "Burkina Faso",
		"BI" => "Burundi",
		"KH" => "Cambodia",
		"CM" => "Cameroon",
		"CA" => "Canada",
		"CT" => "Canton and Enderbury Islands",
		"CV" => "Cape Verde",
		"KY" => "Cayman Islands",
		"CF" => "Central African Republic",
		"TD" => "Chad",
		"CL" => "Chile",
		"CN" => "China",
		"CX" => "Christmas Island",
		"CC" => "Cocos [Keeling] Islands",
		"CO" => "Colombia",
		"KM" => "Comoros",
		"CG" => "Congo - Brazzaville",
		"CD" => "Congo - Kinshasa",
		"CK" => "Cook Islands",
		"CR" => "Costa Rica",
		"HR" => "Croatia",
		"CU" => "Cuba",
		"CY" => "Cyprus",
		"CZ" => "Czech Republic",
		"CI" => "Côte d’Ivoire",
		"DK" => "Denmark",
		"DJ" => "Djibouti",
		"DM" => "Dominica",
		"DO" => "Dominican Republic",
		"NQ" => "Dronning Maud Land",
		"DD" => "East Germany",
		"EC" => "Ecuador",
		"EG" => "Egypt",
		"SV" => "El Salvador",
		"GQ" => "Equatorial Guinea",
		"ER" => "Eritrea",
		"EE" => "Estonia",
		"ET" => "Ethiopia",
		"FK" => "Falkland Islands",
		"FO" => "Faroe Islands",
		"FJ" => "Fiji",
		"FI" => "Finland",
		"FR" => "France",
		"GF" => "French Guiana",
		"PF" => "French Polynesia",
		"TF" => "French Southern Territories",
		"FQ" => "French Southern and Antarctic Territories",
		"GA" => "Gabon",
		"GM" => "Gambia",
		"GE" => "Georgia",
		"DE" => "Germany",
		"GH" => "Ghana",
		"GI" => "Gibraltar",
		"GR" => "Greece",
		"GL" => "Greenland",
		"GD" => "Grenada",
		"GP" => "Guadeloupe",
		"GU" => "Guam",
		"GT" => "Guatemala",
		"GG" => "Guernsey",
		"GN" => "Guinea",
		"GW" => "Guinea-Bissau",
		"GY" => "Guyana",
		"HT" => "Haiti",
		"HM" => "Heard Island and McDonald Islands",
		"HN" => "Honduras",
		"HK" => "Hong Kong SAR China",
		"HU" => "Hungary",
		"IS" => "Iceland",
		"IN" => "India",
		"ID" => "Indonesia",
		"IR" => "Iran",
		"IQ" => "Iraq",
		"IE" => "Ireland",
		"IM" => "Isle of Man",
		"IL" => "Israel",
		"IT" => "Italy",
		"JM" => "Jamaica",
		"JP" => "Japan",
		"JE" => "Jersey",
		"JT" => "Johnston Island",
		"JO" => "Jordan",
		"KZ" => "Kazakhstan",
		"KE" => "Kenya",
		"KI" => "Kiribati",
		"KW" => "Kuwait",
		"KG" => "Kyrgyzstan",
		"LA" => "Laos",
		"LV" => "Latvia",
		"LB" => "Lebanon",
		"LS" => "Lesotho",
		"LR" => "Liberia",
		"LY" => "Libya",
		"LI" => "Liechtenstein",
		"LT" => "Lithuania",
		"LU" => "Luxembourg",
		"MO" => "Macau SAR China",
		"MK" => "Macedonia",
		"MG" => "Madagascar",
		"MW" => "Malawi",
		"MY" => "Malaysia",
		"MV" => "Maldives",
		"ML" => "Mali",
		"MT" => "Malta",
		"MH" => "Marshall Islands",
		"MQ" => "Martinique",
		"MR" => "Mauritania",
		"MU" => "Mauritius",
		"YT" => "Mayotte",
		"FX" => "Metropolitan France",
		"MX" => "Mexico",
		"FM" => "Micronesia",
		"MI" => "Midway Islands",
		"MD" => "Moldova",
		"MC" => "Monaco",
		"MN" => "Mongolia",
		"ME" => "Montenegro",
		"MS" => "Montserrat",
		"MA" => "Morocco",
		"MZ" => "Mozambique",
		"MM" => "Myanmar [Burma]",
		"NA" => "Namibia",
		"NR" => "Nauru",
		"NP" => "Nepal",
		"NL" => "Netherlands",
		"AN" => "Netherlands Antilles",
		"NT" => "Neutral Zone",
		"NC" => "New Caledonia",
		"NZ" => "New Zealand",
		"NI" => "Nicaragua",
		"NE" => "Niger",
		"NG" => "Nigeria",
		"NU" => "Niue",
		"NF" => "Norfolk Island",
		"KP" => "North Korea",
		"VD" => "North Vietnam",
		"MP" => "Northern Mariana Islands",
		"NO" => "Norway",
		"OM" => "Oman",
		"PC" => "Pacific Islands Trust Territory",
		"PK" => "Pakistan",
		"PW" => "Palau",
		"PS" => "Palestinian Territories",
		"PA" => "Panama",
		"PZ" => "Panama Canal Zone",
		"PG" => "Papua New Guinea",
		"PY" => "Paraguay",
		"YD" => "People's Democratic Republic of Yemen",
		"PE" => "Peru",
		"PH" => "Philippines",
		"PN" => "Pitcairn Islands",
		"PL" => "Poland",
		"PT" => "Portugal",
		"PR" => "Puerto Rico",
		"QA" => "Qatar",
		"RO" => "Romania",
		"RU" => "Russia",
		"RW" => "Rwanda",
		"RE" => "Réunion",
		"BL" => "Saint Barthélemy",
		"SH" => "Saint Helena",
		"KN" => "Saint Kitts and Nevis",
		"LC" => "Saint Lucia",
		"MF" => "Saint Martin",
		"PM" => "Saint Pierre and Miquelon",
		"VC" => "Saint Vincent and the Grenadines",
		"WS" => "Samoa",
		"SM" => "San Marino",
		"SA" => "Saudi Arabia",
		"SN" => "Senegal",
		"RS" => "Serbia",
		"CS" => "Serbia and Montenegro",
		"SC" => "Seychelles",
		"SL" => "Sierra Leone",
		"SG" => "Singapore",
		"SK" => "Slovakia",
		"SI" => "Slovenia",
		"SB" => "Solomon Islands",
		"SO" => "Somalia",
		"ZA" => "South Africa",
		"GS" => "South Georgia and the South Sandwich Islands",
		"KR" => "South Korea",
		"ES" => "Spain",
		"LK" => "Sri Lanka",
		"SD" => "Sudan",
		"SR" => "Suriname",
		"SJ" => "Svalbard and Jan Mayen",
		"SZ" => "Swaziland",
		"SE" => "Sweden",
		"CH" => "Switzerland",
		"SY" => "Syria",
		"ST" => "São Tomé and Príncipe",
		"TW" => "Taiwan",
		"TJ" => "Tajikistan",
		"TZ" => "Tanzania",
		"TH" => "Thailand",
		"TL" => "Timor-Leste",
		"TG" => "Togo",
		"TK" => "Tokelau",
		"TO" => "Tonga",
		"TT" => "Trinidad and Tobago",
		"TN" => "Tunisia",
		"TR" => "Turkey",
		"TM" => "Turkmenistan",
		"TC" => "Turks and Caicos Islands",
		"TV" => "Tuvalu",
		"UM" => "U.S. Minor Outlying Islands",
		"PU" => "U.S. Miscellaneous Pacific Islands",
		"VI" => "U.S. Virgin Islands",
		"UG" => "Uganda",
		"UA" => "Ukraine (Україна)",
		"AE" => "United Arab Emirates",
		"GB" => "United Kingdom",
		"US" => "United States",
		"ZZ" => "Unknown or Invalid Region",
		"UY" => "Uruguay",
		"UZ" => "Uzbekistan",
		"VU" => "Vanuatu",
		"VA" => "Vatican City",
		"VE" => "Venezuela",
		"VN" => "Vietnam",
		"WK" => "Wake Island",
		"WF" => "Wallis and Futuna",
		"EH" => "Western Sahara",
		"YE" => "Yemen",
		"ZM" => "Zambia",
		"ZW" => "Zimbabwe",
		"AX" => "Åland Islands",
		"IND-S" => "Коренной индусский программист",
	);
?>