<?php global $_CONFIG; ?>
<!doctype html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="SimplePM programming contests management system">
    <meta name="author" content="Yurij Kadirov and Sirkadirov Team">
    <!--link rel="icon" href="favicon.ico"-->

    <title>$(title) | SimplePM</title>

    <!-- Bootstrap core CSS -->
    <link href="<?=_SPM_assets_?>css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<?=_SPM_assets_?>css/theme.css" rel="stylesheet">

	<!-- Required JavaScript includes -->
	<script src="<?=_SPM_assets_?>js/jquery.min.js"></script>

</head>
<body>