<?php

/*
 * ███████╗██╗███╗   ███╗██████╗ ██╗     ███████╗██████╗ ███╗   ███╗
 * ██╔════╝██║████╗ ████║██╔══██╗██║     ██╔════╝██╔══██╗████╗ ████║
 * ███████╗██║██╔████╔██║██████╔╝██║     █████╗  ██████╔╝██╔████╔██║
 * ╚════██║██║██║╚██╔╝██║██╔═══╝ ██║     ██╔══╝  ██╔═══╝ ██║╚██╔╝██║
 * ███████║██║██║ ╚═╝ ██║██║     ███████╗███████╗██║     ██║ ╚═╝ ██║
 * ╚══════╝╚═╝╚═╝     ╚═╝╚═╝     ╚══════╝╚══════╝╚═╝     ╚═╝     ╚═╝
 *
 * SimplePM WebApp is a part of software product "Automated
 * vefification system for programming tasks "SimplePM".
 *
 * Copyright 2018 Yurij Kadirov
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Visit website for more details: https://spm.sirkadirov.com/
 */

/*
 * Инициализируем соединение с базой
 * данных и получаем его дескриптор.
 */

$database = new mysqli(
    $_CONFIG->getDatabaseConfig()["hostname"],
    $_CONFIG->getDatabaseConfig()["username"],
    $_CONFIG->getDatabaseConfig()["password"],
    $_CONFIG->getDatabaseConfig()["basename"],
    $_CONFIG->getDatabaseConfig()["portname"]
);

/*
 * Производим проверку на наличие ошибок
 * при попытке подключения к удалённой
 * базе данных, и, в случае их нахождения,
 * выбрасываем исключение.
 */

if ($database->connect_errno)
    die("<h1>Oops, database connection error! Please, try again later!</h1>");

$database->set_charset("utf8");

?>